### ISSUE TITLE
Can't connect to Spydroid stream

### ISSUE THREAD

**Issue by atduskgreg** [bakercp/IPCAM2SYPHON#1]
I'm trying to connect IPCAM2SYPHON to Spydroid serving an IP Camera feed from Android. I can connect to the stream in VLC successfully, but when I put the same URL into the IPCAM2SYPHON config file, it fails to connnect:

![screen shot 2013-09-29 at 12 02 52 pm](https://f.cloud.github.com/assets/165/1233350/b15f2492-2920-11e3-9413-fabedf531201.png)

Spydroid runs on port 8080:

```
http://18.189.9.13:8080/spydroid.sdp?h264=640-30
```

**Comment by bakercp** [comment]
Hey there, my guess is that the spydroid stream is h264 / sdp rather than mjpeg (which ofxIpVideoGrabber works with).

Just noticed this on their site "Two video encoders are available for the video streaming: H.263 and H.264. For sound streaming AMR and AAC are available."

So ... not sure what to say.  I feel like someone was working on h264 streaming ... alternatively it may be possible with the existing `ofQTKitVideoPlayer` ... not sure.

Theoretically you could also use my "https://github.com/bakercp/ofxIpVideoServer" on Android to send a video stream to my `ofxIpVideoGrabber` using the camera.  It is pure Poco, so no other libraries are needed ... I've done it with ipad / raspberry pi, etc.

Sorry there isn't any easy answer!

**Comment by atduskgreg** [comment]
Thanks for looking into this! I just started into the route of trying ofxIpVideoServer on iOS. I'm getting an error so I created an issue over in that project. Probably has to do with the fact that I'm on ios7.

**Comment by bakercp** [comment]
Closing this for now since the issue was moved.
